# Generated by Django 5.2.11 on 2026-03-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0116_advisoryv2_advisory_content_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisoryreference",
            name="archive_url",
            field=models.URLField(
                help_text="URL to the backup vulnerability reference", max_length=1024, null=True
            ),
        ),
    ]
